language: c

env:
  DOCKER_COMPOSE_VERSION: 1.5.2

sudo: false

services:
  - docker

addons:
  ssh_known_hosts: github.com

before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in travis.rsa.enc -out travis.rsa -d
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - cp travis.rsa /home/travis/.ssh/id_rsa
  - chmod 600 /home/travis/.ssh/id_rsa
  - ssh-keyscan -t rsa github.com >> /home/travis/.ssh/known_hosts
  - ls -al /home/travis/.ssh
  - ssh -Tv git@github.com || true
  - docker-compose build
  - docker-compose up -d
  - timeout 20 docker-compose logs committer
  - docker-compose stop
  - timeout 5 docker-compose logs committer2
