malamute:
  image: zeromqorg/malamute
  volumes:
   - ./malamute/malamute.cfg:/opt/malamute.cfg
  ports:
   - "9999:9999"
  command: ['malamute', '-f', '/opt/malamute.cfg']
trigger:
  build: trigger
  volumes:
   - ./mdh.py:/opt/mdh.py
  links:
   - malamute
  command: ['python3', '/opt/mdh.py', 'publish', 'tcp://malamute:9999', 'https://github.com/gotcha/maitredhotel']
committer:
  image: maitredhotel_trigger
  volumes:
   - ./mdh.py:/opt/mdh.py
   - ./mdh_init_and_commit.sh:/opt/mdh_init_and_commit.sh
   - /Users/gotcha/.ssh:/home/zmq/.ssh
  links:
   - malamute
  command: ['/opt/mdh_init_and_commit.sh']
